name: Build mkosi

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: systemd/mkosi@v25.3
      - name: Run mkosi
        run: mkosi build
