name: Ruby CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install ruby
        runt: apt-get update && apt-get install ruby bundler -y
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
