= Systemd Portable Service installation

CollectRack can be installed as a https://systemd.io/PORTABLE_SERVICES/[Portable Service] for use with systemd. This is akin to using an OCI image but it's native to systemd. The current build relies on using OpenSUSE as a base and results in a root filesystem of about 36MB.

== Installation

=== Automated installation
Collectrack can be installed as a https://www.freedesktop.org/software/systemd/man/latest/sysupdate.d.html[sysupdate.d(8)] component. This allows for automatically downloading and mataining the latest portable release.

You can execute the following install script to install the component.

```
curl  https://raw.githubusercontent.com/LevitatingBusinessMan/collectrack/refs/heads/master/scripts/portable-install.sh | sh
```

You can also manually download the `portable.target` file and place it at `/etc/sysupdate.collectrack.d`. See the install script for reference.

=== Manual installation

Find the latest release at https://github.com/LevitatingBusinessMan/collectrack/releases/latest and download the portable rootfs (`collectrack_x.y.z-portable.tar.xz`) asset.

Run the following commands as root:

```SH
# Import the image using importctl(1)
importctl -P import-tar collectrack_x.y.z-portable.tar.xz --verify=checksum
# Attach the rootfs using portablectl(1)
portablectl attach collectrack_x.y.z-portable
# Start the attached collectrack.service
systemctl start collectrack.service
```

== Configuring the service
CollectRack needs read access to `/var/lib/collectd` and `/etc/collectd.conf`. The default `collectrack.service` configuration will attempt to mount these. If these paths aren't readable, the `collectrack.service` will fail.

To change this and other behaviour the `.service` file may be edited via an override:

```
systemctl cat collectrack.service # view the current configuration
systemctl edit collectrack.service # adjust as needed
```

An example override could be:
```
[Service]
# Run as collectd group for reading /etc/collectd.conf
Group=collectd
# Bind correct paths
BindReadOnlyPaths=/usr/etc/collectd.conf /media/hdd/collectd
# Point CollectRack to the collectd.conf
Environment=COLLECTD_CONFIG=/usr/etc/collectd.conf
# Listen on a different port
ExecStart=
ExecStart=/opt/collectrack/bin/puma -e production -p 8080
```

Per default the service runs with `DynamicUser=yes` but also `Group=collectd`. So to allow read access to the collectd.conf you could do `groupadd collectd && chown :collectd /etc/collectd.conf`.

If you keep running into permission issues, you can choose to attach the images with the "trusted" profile via the `-p` flag on `portablectl(1)`.

For the `FLUSH` feature, collectrack needs write access to `/run/collectd.sock`. However, the `default` profile already mounts `/run` as writable.
The path and permissions for the socket are configured in the `Plugin unixsock` section of `collectd.conf`.

=== Using a unix socket
Use the following systemd override.
```
[Service]
ExecStart=
ExecStart=/opt/collectrack/bin/puma -e production -b unix:/run/collectrack/collectrack.sock
RuntimeDirectory=collectrack
```

== Updating
When using the https://www.freedesktop.org/software/systemd/man/latest/sysupdate.d.html[sysupdate.d(8)] target you do the following:

```
/lib/systemd/systemd-sysupdate -C collectrack update
portablectl reattach --now collectrack
```

The current version will always be tracked via a symlink at `/var/lib/portables/collectrack`.

You can view the version of a running instance via reading the HTTP headers: `curl -Is http://127.0.0.1:3344 | grep x-collectrack`.

== See also
- https://systemd.io/PORTABLE_SERVICES/[Portable Services]
- https://manpages.opensuse.org/Tumbleweed/systemd-container/importctl.1.en.html[importctl(1)]
- https://manpages.opensuse.org/Tumbleweed/systemd-portable/portablectl.1.en.html[portablectl(1)]
