= Systemd Portable Service installation

CollectRack can be installed as a https://systemd.io/PORTABLE_SERVICES/[Portable Service] for use with systemd. This is akin to using an OCI image but it's native to systemd. The current build relies on using OpenSUSE as a base and results in a root filesystem of about 36MB.

== Installation

Find the latest release at https://github.com/LevitatingBusinessMan/collectrack/releases and download the portable rootfs (`collectrack_x.y.z-portable.tar.xz`) asset.

Run the following commands as root:

```SH
# Import the image using importctl(1)
importctl -P import-tar collectrack_x.y.z-portable.tar.xz --verify=checksum
# Attach the rootfs using portablectl(1)
portablectl attach collectrack_x.y.z-portable
# Start the attached collectrack.service
systemctl start collectrack.service
```

== Configuring the service
CollectRack needs read access to `/var/lib/collectd` and `/etc/collectd.conf`. The default `collectrack.service` configuration will attempt to mount these. If these directories don't exist on the host, the service will fail.

To change this and other behaviour the `.service` file may be edited via an override:

```
systemctl cat collectrack.service # view the current configuration
systemctl edit collectrack.service # adjust as needed
```

An example overwrite would be:
```
[Service]
# Run as root for reading /etc/collectd.conf
DynamicUser=no
# Bind correct paths
BindReadOnlyPaths=/usr/etc/collectd.conf /media/hdd/collectd
Environment=COLLECTD_CONFIG=/usr/etc/collectd.conf
```

For the `FLUSH` feature, collectrack needs write access to `/run/collectd.sock`. However, the `default` profile already mounts `/run` as writable.

== Updating
To update collectrack just install and enable a new portable rootfs.
```
importctl -P import-tar collectrack_new.tar.xz --verify=checksum
portablectl detach --now --enable collectrack_old
portablectl attach --now --enable collectrack_new
portablectl remove collectrack_old
```

One could theoretically automate this process via periodic importctl calls.

If you're images are not versioned, you can always get the current version via reading the HTTP headers: `curl -Is http://127.0.0.1:3344 | grep x-collectrack`.

= See also
- https://systemd.io/PORTABLE_SERVICES/[Portable Services]
- https://manpages.opensuse.org/Tumbleweed/systemd-container/importctl.1.en.html[importctl(1)]
- https://manpages.opensuse.org/Tumbleweed/systemd-portable/portablectl.1.en.html[portablectl(1)]
